/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import connect.Connect;
import java.awt.Color;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelCheckIn;
import model.ModelCheckInv2;
import model.ModelCheckOut;
import model.ModelCheckOutv2;
import model.ModelPhong;
import model.ModelPhongv2;
import model.ModelServiceRentv2;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author TeeDee
 */
public class FormCheckOut extends javax.swing.JPanel {

    /**
     * Creates new form FormCheckOut
     */
    public FormCheckOut() {
        initComponents();
    }
    
    Connect cn = new Connect();
    Connection conn;
    DefaultTableModel tbmodel;

    private String username, password, quyen, DisplayName;
    
    public FormCheckOut(String username, String password, String DisplayName, String quyen) {
        initComponents();
        this.username = username;
        this.password = password;
        this.DisplayName = DisplayName;
        this.quyen = quyen;
        
        
        initCombobox_maphieudathong();
  
       

        inittable();
        loaddulieu1();
    }
    
    private void inittable() {
        tbmodel = new DefaultTableModel();
        tbmodel.setColumnIdentifiers(new String[]{"Mã hóa đơn phòng", "Mã phiếu đặt phòng",  "Ngày thuê phòng", "Ngày trả phòng", "Mã phòng", "Tên phòng", "Loại phòng",  "Giá phòng","Giảm giá", "VAT","Giá hóa đơn", "Ngày lập hóa đơn"});
        TBcheckout.setModel(tbmodel);
    }
    
     public void loaddulieu1() {
        try {
            ModelCheckOut ql = new ModelCheckOut();
            ArrayList<ModelCheckOutv2> list = ql.findALL();
            tbmodel.setRowCount(0);
            for (ModelCheckOutv2 p : list) {
                tbmodel.addRow(new Object[]{
                    p.getMaHoaDonPhong(), p.getMaPhieuDatPhong(), p.getNgayThuePhong(), p.getNgayTraPhong(), p.getMaPhong(),p.getTenPhong(), p.getLoaiPhong(),  p.getFormattedGia(), p.getFormattedPercentage(),p.getFormattedVAT(), p.getFormattedGiahd(), p.getNgayLapHoaDon()
                });
            }
            tbmodel.fireTableDataChanged();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error " + e.getMessage());
            e.printStackTrace();
        }

    }
     
    private void initCombobox_maphieudathong() {
        try {
            conn = cn.getConnection();
            //select MaPhieuDatPhong from phieudatphong where booked_status = 1 and isvisible = 1

            String sql = "select MaPhieuDatPhong from phieudatphong where booked_status = 1 and isvisible = 1 and MaPhieuDatPhong not in (select MaPhieuDatPhong from HoaDonPhong) ";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            cmbmaphieudatphong.removeAllItems();
          
            while (rs.next()) {
                cmbmaphieudatphong.addItem(rs.getString("MaPhieuDatPhong"));
            }
            rs.close();
            pstmt.close();
            conn.close();
        } catch (Exception e) {
           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel5 = new swing.RoundPanel();
        jLabel10 = new javax.swing.JLabel();
        btnEdit = new swing.Button();
        btnAdd = new swing.Button();
        btnDelete = new swing.Button();
        btnRefresh = new swing.Button();
        cmbmaphieudatphong = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jDateChooserngaylaphd = new com.toedter.calendar.JDateChooser();
        btnPay = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        txtMaphieutraphong = new component.TextField();
        txtMaPhong = new component.TextField();
        txtTenPhong = new component.TextField();
        txtloaiphong = new component.TextField();
        txtGiaPhong = new component.TextField();
        txtGiahd = new component.TextField();
        txtVAT = new component.TextField();
        txtNgaythuephong = new component.TextField();
        txtNgayTraPhong = new component.TextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGiamGia = new component.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBcheckout = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        roundPanel5.setBackground(new java.awt.Color(36, 87, 157));
        roundPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin trả phòng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mã phiếu đặt phòng:");

        btnEdit.setText("Sửa");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnAdd.setText("Thêm");
        btnAdd.setEnabled(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnRefresh.setText("Làm mới");
        btnRefresh.setEnabled(false);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        cmbmaphieudatphong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbmaphieudatphongItemStateChanged(evt);
            }
        });
        cmbmaphieudatphong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbmaphieudatphongMousePressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Ngày lập HĐ:");

        btnPay.setBackground(new java.awt.Color(255, 102, 102));
        btnPay.setText("Tính tiền");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        btnReport.setBackground(new java.awt.Color(255, 99, 76));
        btnReport.setText("In Report");
        btnReport.setEnabled(false);
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        txtMaphieutraphong.setLabelText("Mã phiếu trả phòng");
        txtMaphieutraphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaphieutraphongActionPerformed(evt);
            }
        });

        txtMaPhong.setEditable(false);
        txtMaPhong.setLabelText("Mã phòng");
        txtMaPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaPhongActionPerformed(evt);
            }
        });

        txtTenPhong.setEditable(false);
        txtTenPhong.setLabelText("Tên phòng");
        txtTenPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenPhongActionPerformed(evt);
            }
        });

        txtloaiphong.setEditable(false);
        txtloaiphong.setLabelText("Loại phòng");
        txtloaiphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtloaiphongActionPerformed(evt);
            }
        });

        txtGiaPhong.setEditable(false);
        txtGiaPhong.setLabelText("Giá phòng");
        txtGiaPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaPhongActionPerformed(evt);
            }
        });

        txtGiahd.setEditable(false);
        txtGiahd.setLabelText("Giá hóa đơn");
        txtGiahd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiahdActionPerformed(evt);
            }
        });

        txtVAT.setEditable(false);
        txtVAT.setLabelText("Giá VAT");
        txtVAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVATActionPerformed(evt);
            }
        });

        txtNgaythuephong.setEditable(false);
        txtNgaythuephong.setLabelText("Ngày thuê phòng");
        txtNgaythuephong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaythuephongActionPerformed(evt);
            }
        });

        txtNgayTraPhong.setEditable(false);
        txtNgayTraPhong.setLabelText("Ngày trả phòng");
        txtNgayTraPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayTraPhongActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("*");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("*");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("*");

        txtGiamGia.setEditable(false);
        txtGiamGia.setLabelText("Giảm giá");
        txtGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiamGiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundPanel5Layout = new javax.swing.GroupLayout(roundPanel5);
        roundPanel5.setLayout(roundPanel5Layout);
        roundPanel5Layout.setHorizontalGroup(
            roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(roundPanel5Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNgaythuephong, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayTraPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundPanel5Layout.createSequentialGroup()
                        .addGroup(roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(roundPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbmaphieudatphong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(roundPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooserngaylaphd, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtMaphieutraphong, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel5Layout.createSequentialGroup()
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                            .addComponent(txtTenPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtloaiphong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel5Layout.createSequentialGroup()
                                .addGroup(roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVAT, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtGiaPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtGiahd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))))))
                .addGap(54, 54, 54))
        );
        roundPanel5Layout.setVerticalGroup(
            roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(roundPanel5Layout.createSequentialGroup()
                        .addGroup(roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaphieutraphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbmaphieudatphong, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(txtNgaythuephong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNgayTraPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserngaylaphd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(roundPanel5Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel3)))))
                    .addGroup(roundPanel5Layout.createSequentialGroup()
                        .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtloaiphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGiahd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TBcheckout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TBcheckout.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TBcheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBcheckoutMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBcheckout);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Thông tin trả phòng:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roundPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        Date selectedDate = jDateChooserngaylaphd.getDate();
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(selectedDate);

        int year = calendar.get(Calendar.YEAR);
        int month = calendar.get(Calendar.MONTH) + 1; // Tháng bắt đầu từ 0, nên cộng thêm 1 để có giá trị tháng thực
        int day = calendar.get(Calendar.DAY_OF_MONTH);
        String ngayhd = year + "-" + month + "-" + day;

        StringBuilder sb = new StringBuilder();
        if (txtMaphieutraphong.getText().equals("")) {
            sb.append("Mã phiếu trả phòng không được để trống");
            txtMaphieutraphong.setBackground(Color.red);

        } else {
            txtMaphieutraphong.setBackground(Color.white);
 
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb);
        }
        String Maphieudatphong = cmbmaphieudatphong.getSelectedItem().toString();

        try {
            ModelCheckOutv2 ci = new ModelCheckOutv2();
            ci.setMaHoaDonPhong(txtMaphieutraphong.getText());
            ci.setNgayLapHoaDon(ngayhd);
            ci.setMaPhieuDatPhong(Maphieudatphong);

            ModelCheckOut ql1 = new ModelCheckOut();
            ql1.update(ci);

            JOptionPane.showMessageDialog(this, "Lưu thành công!!!");
            
            
            loaddulieu1();
        } catch (Exception e) {
            //            JOptionPane.showMessageDialog(this, "error " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Mã hóa đơn phòng này đã tồn tại, nếu muốn thêm với mã hóa đơn phòng này vui lòng xóa phiếu đặt phòng trong db");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:

        Date selectedDate = jDateChooserngaylaphd.getDate();
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(selectedDate);

        int year = calendar.get(Calendar.YEAR);
        int month = calendar.get(Calendar.MONTH) + 1; // Tháng bắt đầu từ 0, nên cộng thêm 1 để có giá trị tháng thực
        int day = calendar.get(Calendar.DAY_OF_MONTH);
        String ngayhd = year + "-" + month + "-" + day;

        StringBuilder sb = new StringBuilder();
        if (txtMaphieutraphong.getText().equals("")) {
            sb.append("Mã phiếu trả phòng không được để trống");
            txtMaphieutraphong.setBackground(Color.red);

        } else {
            txtMaphieutraphong.setBackground(Color.white);
            
            String Maphieuthuephong = cmbmaphieudatphong.getSelectedItem().toString();

            try {
                ModelCheckOutv2 ci = new ModelCheckOutv2();
                ci.setMaHoaDonPhong(txtMaphieutraphong.getText());
                ci.setNgayLapHoaDon(ngayhd);
                ci.setMaPhieuDatPhong(Maphieuthuephong);

                ModelCheckOut ql1 = new ModelCheckOut();
                ql1.insert(ci);

                JOptionPane.showMessageDialog(this, "Lưu thành công!!!");
                
                loaddulieu1();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Mã hóa đơn phòng này đã tồn tại, nếu muốn thêm với mã hóa đơn phòng này vui lòng xóa phiếu đặt phòng trong db");
                e.printStackTrace();
            }
            
            
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb);
        }

        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        StringBuilder sb = new StringBuilder();
        if (txtMaphieutraphong.getText().equals("")) {
            sb.append("Mã phiếu trả phòng không được để trống");
            txtMaphieutraphong.setBackground(Color.red);

        } else {
            txtMaphieutraphong.setBackground(Color.white);
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb);
        }
        try {
            ModelCheckOutv2 ci = new ModelCheckOutv2();//MaHoaDonPhong
            ci.setMaHoaDonPhong(txtMaphieutraphong.getText());

            ModelCheckOut ql1 = new ModelCheckOut();
            ql1.deletecomeroot(ci);

            JOptionPane.showMessageDialog(this, "Lưu thành công!!!");
            
            
            int row = TBcheckout.getSelectedRow();
            if (row >= 0) {
                String maphong = TBcheckout.getValueAt(row, 5).toString();
                
                ModelPhongv2 p = new ModelPhongv2();
                p.setMaPhong(maphong);

                ModelPhong ql = new ModelPhong();
                ql.updateTT3(p);
                
  
            }
            
            
            loaddulieu1();
        } catch (Exception e) {
            //            JOptionPane.showMessageDialog(this, "error " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Mã phiếu đặt phòng này đã tồn tại, nếu muốn thêm với mã phiếu đặt phòng này vui lòng xóa phiếu đặt phòng trong db");
            e.printStackTrace();
        }

        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void cmbmaphieudatphongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbmaphieudatphongItemStateChanged
        // TODO add your handling code here:
        String Mapdp = cmbmaphieudatphong.getSelectedItem().toString();
        try {
            ModelCheckOut ql = new ModelCheckOut();

            ModelCheckOutv2 ttp = ql.findByID(Mapdp);
            if (ttp != null) {
                txtNgaythuephong.setText(ttp.getNgayThuePhong());
                txtNgayTraPhong.setText(ttp.getNgayTraPhong());
                txtMaPhong.setText(ttp.getMaPhong());
                txtTenPhong.setText(ttp.getTenPhong());
                txtloaiphong.setText(ttp.getLoaiPhong());
                txtGiamGia.setText(ttp.getFormattedPercentage());
                txtGiaPhong.setText(ttp.getFormattedGia());
            } else {
                JOptionPane.showMessageDialog(this, "Không tim thấy mã phiếu thuê phòng");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_cmbmaphieudatphongItemStateChanged

    private void TBcheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBcheckoutMouseClicked
        // TODO add your handling code here:
        int row = TBcheckout.getSelectedRow();

        if (row >= 0) {
            txtMaphieutraphong.setText(TBcheckout.getValueAt(row, 0).toString());

            String maphieudatphong = TBcheckout.getValueAt(row, 1).toString();
            System.out.println("" + maphieudatphong);
            cmbmaphieudatphong.setSelectedItem(maphieudatphong);
            
            
            txtNgaythuephong.setText(TBcheckout.getValueAt(row, 2).toString());
            txtNgayTraPhong.setText(TBcheckout.getValueAt(row, 3).toString());
            
            
            
            txtMaPhong.setText(TBcheckout.getValueAt(row, 4).toString());
            txtTenPhong.setText(TBcheckout.getValueAt(row, 5).toString());
            txtloaiphong.setText(TBcheckout.getValueAt(row, 6).toString());


            txtGiaPhong.setText(TBcheckout.getValueAt(row, 7).toString());
            txtGiamGia.setText(TBcheckout.getValueAt(row, 8).toString());
            txtVAT.setText(TBcheckout.getValueAt(row, 9).toString());
            txtGiahd.setText(TBcheckout.getValueAt(row, 10).toString());
            

            String ngaylaphd = TBcheckout.getValueAt(row, 11).toString();

            try {
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // Định dạng của chuỗi ngày
                Date selectedDate = dateFormat.parse(ngaylaphd); // Phân tích chuỗi thành đối tượng Date
                jDateChooserngaylaphd.setDate(selectedDate); // Đặt giá trị ngày cho JDateChooser
            } catch (ParseException e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_TBcheckoutMouseClicked

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
        btnAdd.setEnabled(true);
        btnEdit.setEnabled(true);
        btnDelete.setEnabled(true);
        btnRefresh.setEnabled(true);
        btnReport.setEnabled(true);

        String tmp = txtGiaPhong.getText();
        DecimalFormat decimalFormat = new DecimalFormat("#,### VND");

        String giamgia = txtGiamGia.getText();
        String giamgianotpercent = giamgia.replace("%", "");
        int dis = Integer.parseInt(giamgianotpercent); 
        
        try {
            Number giaNumber = decimalFormat.parse(tmp);
            // Lấy giá trị số từ đối tượng Number
            Float gia = giaNumber.floatValue();
            
            System.out.println(gia);

//            Date date1 = jDateChooserngaythuephong.getDate();
            String dateString1 = txtNgaythuephong.getText();
            String dateString2 = txtNgayTraPhong.getText();
            
            
            if (dateString1 != null && dateString2 != null) {
                
                // Định dạng của chuỗi ngày tháng
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

                // Chuyển đổi chuỗi thành đối tượng LocalDate
                LocalDate date1 = LocalDate.parse(dateString1, formatter);
                LocalDate date2 = LocalDate.parse(dateString2, formatter);
                
                // Tính khoảng cách giữa hai ngày bằng Period
                float daysDifference = ChronoUnit.DAYS.between(date1, date2);
                System.out.println("Difference in days: " + daysDifference);
                
                
                Float giaphong;
                giaphong = (float) (daysDifference * gia);
                float vat = (float) giaphong * 10 /100;
                
                float discount = (float) giaphong * dis /100;
                System.out.println("giá phòng "+ giaphong +" vat "+ vat + " dis "+ discount);
                
                float giahdend = giaphong + vat - discount;
                
                BigDecimal giahd = BigDecimal.valueOf(giahdend);
                BigDecimal gvat = BigDecimal.valueOf(vat);

                ModelCheckOutv2 sr = new ModelCheckOutv2();
                sr.setGiaHD(giahd);
                sr.setVAT(gvat);
                String formattedhoadon = sr.getFormattedGiahd();
                String formattedvat = sr.getFormattedVAT();
                txtGiahd.setText(formattedhoadon);
                txtVAT.setText(formattedvat);
            }
            


        } catch (ParseException ex) {
            Logger.getLogger(FormServiceRent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
       
        
        if (txtMaphieutraphong.getText().equals("")==true) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn mã phiếu trả phòng");
        } else {
            try {
                Map<String, Object> map = new HashMap<>();
                JasperReport rpt = JasperCompileManager.compileReport("src/report/rpCheckOut.jrxml");
                map.put("mahoadonphong", txtMaphieutraphong.getText());
                conn = cn.getConnection();
                JasperPrint p = JasperFillManager.fillReport(rpt, map, conn);
                JasperViewer.viewReport(p, false);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(this, ex.toString());
            }
        }
    }//GEN-LAST:event_btnReportActionPerformed

    private void txtMaphieutraphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaphieutraphongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaphieutraphongActionPerformed

    private void txtMaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaPhongActionPerformed

    private void txtTenPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenPhongActionPerformed

    private void txtloaiphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtloaiphongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtloaiphongActionPerformed

    private void txtGiaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaPhongActionPerformed

    private void txtGiahdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiahdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiahdActionPerformed

    private void txtVATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVATActionPerformed

    private void txtNgaythuephongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaythuephongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaythuephongActionPerformed

    private void txtNgayTraPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayTraPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayTraPhongActionPerformed

    private void txtGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiamGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiamGiaActionPerformed

    private void cmbmaphieudatphongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbmaphieudatphongMousePressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cmbmaphieudatphongMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TBcheckout;
    private swing.Button btnAdd;
    private swing.Button btnDelete;
    private swing.Button btnEdit;
    private javax.swing.JButton btnPay;
    private swing.Button btnRefresh;
    private javax.swing.JButton btnReport;
    private javax.swing.JComboBox<String> cmbmaphieudatphong;
    private com.toedter.calendar.JDateChooser jDateChooserngaylaphd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private swing.RoundPanel roundPanel5;
    private component.TextField txtGiaPhong;
    private component.TextField txtGiahd;
    private component.TextField txtGiamGia;
    private component.TextField txtMaPhong;
    private component.TextField txtMaphieutraphong;
    private component.TextField txtNgayTraPhong;
    private component.TextField txtNgaythuephong;
    private component.TextField txtTenPhong;
    private component.TextField txtVAT;
    private component.TextField txtloaiphong;
    // End of variables declaration//GEN-END:variables
}
