/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import connect.Connect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelStaff;
import model.ModelStaffv2;

/**
 *
 * @author TeeDee
 */
public class FormQLStaff extends javax.swing.JPanel {

    public FormQLStaff() {
        initComponents();
    }
    Connect cn = new Connect();
    Connection conn;
    private String username, password, quyen, DisplayName;
     DefaultTableModel tbmodel;
    
    
    public FormQLStaff(String username, String password, String DisplayName, String quyen) {
        initComponents();
        this.username = username;
        this.password = password;
        this.DisplayName = DisplayName;
        this.quyen = quyen;
        inittablenhanvien();
        loadthongtinnhanvien();
     
    }
    
    private void inittablenhanvien() {
        tbmodel = new DefaultTableModel();
        tbmodel.setColumnIdentifiers(new String[]{"Mã nhân viên", "Họ nhân viên", "Tên nhân viên", "Giới tính", "Địa chỉ", "Ngày sinh", "Số điện thoại", "Email", "Nơi sinh", "Ngày vào làm"});
        tbNHANVIEN.setModel(tbmodel);
    }

    public void loadthongtinnhanvien() {
        try {
            ModelStaff ql = new ModelStaff();
            ArrayList<ModelStaffv2> list = ql.findALL();
            tbmodel.setRowCount(0);
            for (ModelStaffv2 nv : list) {
                tbmodel.addRow(new Object[]{
                    nv.getMaNV(), nv.getHoNV(), nv.getTenNV(), nv.getGioitinh(), nv.getDiaChi(), nv.getNgaySinh(), nv.getDienThoai(), nv.getEmail(), nv.getNoiSinh(), nv.getNgayVaoLam()
                });
            }
            tbmodel.fireTableDataChanged();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error " + e.getMessage());
            e.printStackTrace();
        }

    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        roundPanel1 = new swing.RoundPanel();
        roundPanel2 = new swing.RoundPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtMANHANVIEN = new javax.swing.JTextField();
        txtHONHANVIEN = new javax.swing.JTextField();
        txtTENNHANVIEN = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        RBNNam = new javax.swing.JRadioButton();
        RBNNNU = new javax.swing.JRadioButton();
        txtSODIENTHOAI = new javax.swing.JTextField();
        txtEMAIL = new javax.swing.JTextField();
        txtNOISINH = new javax.swing.JTextField();
        txtDIACHI = new javax.swing.JTextField();
        btnAdd = new swing.Button();
        btnEdit = new swing.Button();
        bthDelete = new swing.Button();
        btnAdd3 = new swing.Button();
        jDateChooserNgaySInh = new com.toedter.calendar.JDateChooser();
        jDateChooserNgayVaoLam = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbNHANVIEN = new javax.swing.JTable();
        panelBorder2 = new swing.PanelBorder();
        btnSearch = new swing.Button();
        btnView = new swing.Button();
        rbMANHANVIEN = new javax.swing.JRadioButton();
        txtSEARCHMANV = new javax.swing.JTextField();
        rbSDT = new javax.swing.JRadioButton();
        txtsearchsdt = new javax.swing.JTextField();
        rbTENNHANVIEN = new javax.swing.JRadioButton();
        txtsearchtennv = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();

        roundPanel2.setBackground(new java.awt.Color(36, 87, 157));
        roundPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        roundPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Mã nhân viên:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Họ nhân viên:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Tên nhân viên:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Địa chỉ:");

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Giới tính:");

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Ngày sinh:");

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Email:");

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Số điện thoại:");

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Nơi sinh:");

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Ngày vào làm:");

        RBNNam.setBackground(new java.awt.Color(36, 87, 157));
        buttonGroup1.add(RBNNam);
        RBNNam.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        RBNNam.setForeground(new java.awt.Color(255, 255, 255));
        RBNNam.setText("Nam");

        RBNNNU.setBackground(new java.awt.Color(36, 87, 157));
        buttonGroup1.add(RBNNNU);
        RBNNNU.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        RBNNNU.setForeground(new java.awt.Color(255, 255, 255));
        RBNNNU.setText("Nữ");

        txtSODIENTHOAI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        bthDelete.setText("Xóa");
        bthDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthDeleteActionPerformed(evt);
            }
        });

        btnAdd3.setText("Làm mới");
        btnAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44))
                        .addGap(42, 42, 42)
                        .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTENNHANVIEN, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(txtMANHANVIEN)
                            .addComponent(txtHONHANVIEN)
                            .addGroup(roundPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(RBNNam, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(RBNNNU)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jDateChooserNgaySInh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(bthDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jDateChooserNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(roundPanel2Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btnAdd3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel45)
                            .addComponent(jLabel46))
                        .addGap(48, 48, 48)
                        .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSODIENTHOAI)
                            .addComponent(txtDIACHI)
                            .addComponent(txtNOISINH)
                            .addComponent(txtEMAIL))))
                .addGap(97, 97, 97))
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txtMANHANVIEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSODIENTHOAI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel46))))
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txtHONHANVIEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(txtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtTENNHANVIEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47)
                    .addComponent(txtNOISINH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jLabel25)
                    .addComponent(RBNNam)
                    .addComponent(RBNNNU)
                    .addComponent(txtDIACHI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel44)
                        .addComponent(jLabel48))
                    .addComponent(jDateChooserNgaySInh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bthDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        tbNHANVIEN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbNHANVIEN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbNHANVIEN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNHANVIENMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbNHANVIEN);

        panelBorder2.setBackground(new java.awt.Color(36, 87, 157));
        panelBorder2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20), new java.awt.Color(255, 255, 255))); // NOI18N
        panelBorder2.setForeground(new java.awt.Color(255, 255, 255));

        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnView.setText("Xem");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        rbMANHANVIEN.setBackground(new java.awt.Color(36, 87, 157));
        buttonGroup2.add(rbMANHANVIEN);
        rbMANHANVIEN.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rbMANHANVIEN.setForeground(new java.awt.Color(255, 255, 255));
        rbMANHANVIEN.setText("Mã nhân viên:");

        rbSDT.setBackground(new java.awt.Color(36, 87, 157));
        buttonGroup2.add(rbSDT);
        rbSDT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rbSDT.setForeground(new java.awt.Color(255, 255, 255));
        rbSDT.setText("Số điện thoại:");

        rbTENNHANVIEN.setBackground(new java.awt.Color(36, 87, 157));
        buttonGroup2.add(rbTENNHANVIEN);
        rbTENNHANVIEN.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rbTENNHANVIEN.setForeground(new java.awt.Color(255, 255, 255));
        rbTENNHANVIEN.setText("Tên nhân viên:");

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbMANHANVIEN)
                    .addComponent(rbSDT)
                    .addComponent(rbTENNHANVIEN))
                .addGap(18, 18, 18)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtsearchtennv, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(txtsearchsdt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSEARCHMANV, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(52, 52, 52)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbMANHANVIEN)
                            .addComponent(txtSEARCHMANV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbSDT)
                            .addComponent(txtsearchsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbTENNHANVIEN)
                            .addComponent(txtsearchtennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelBorder2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Thông tin nhân viên:");

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Date selectedDate = jDateChooserNgaySInh.getDate();
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(selectedDate);

        int year = calendar.get(Calendar.YEAR);
        int month = calendar.get(Calendar.MONTH) + 1; // Tháng bắt đầu từ 0, nên cộng thêm 1 để có giá trị tháng thực
        int day = calendar.get(Calendar.DAY_OF_MONTH);
        String ngaysinh = year + "-" + month + "-" + day;
        
        
//        String ngay = cmbNGAY1.getSelectedItem().toString();
//        String thang = cmbTHANG1.getSelectedItem().toString();
//        String nam = cmbNAM1.getSelectedItem().toString();
//        String ngaysinh = nam + "-" + thang + "-" + ngay;
       
        Date selectedDate1 = jDateChooserNgayVaoLam.getDate();
        Calendar calendar1 = Calendar.getInstance();
        calendar1.setTime(selectedDate1);
        
        int year1 = calendar1.get(Calendar.YEAR);
        int month1 = calendar1.get(Calendar.MONTH) + 1; // Tháng bắt đầu từ 0, nên cộng thêm 1 để có giá trị tháng thực
        int day1 = calendar1.get(Calendar.DAY_OF_MONTH);
        String ngaysinh1 = year1 + "-" + month1 + "-" + day1;

    
//        String ngay1 = cmbNGAY2.getSelectedItem().toString();
//        String thang1 = cmbTHANG2.getSelectedItem().toString();
//        String nam1 = cmbNAM2.getSelectedItem().toString();
//        String ngaysinh1 = nam1 + "-" + thang1 + "-" + ngay1;
       

        StringBuilder sb = new StringBuilder();
        if (txtMANHANVIEN.getText().equals("")) {
            sb.append("mã nhân viên không được để trống");
            txtMANHANVIEN.setBackground(Color.red);

        } else {
            txtMANHANVIEN.setBackground(Color.white);
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb);
        }
        try {
            ModelStaffv2 nv = new ModelStaffv2();
            nv.setMaNV(txtMANHANVIEN.getText());
            nv.setHoNV(txtHONHANVIEN.getText());
            nv.setTenNV(txtTENNHANVIEN.getText());
            nv.setGioitinh(RBNNam.isSelected() ? 1 : 0);
            nv.setDiaChi(txtDIACHI.getText());
            nv.setNgaySinh(ngaysinh);
            nv.setDienThoai(txtSODIENTHOAI.getText());
            nv.setEmail(txtEMAIL.getText());
            nv.setNoiSinh(txtNOISINH.getText());
            nv.setNgayVaoLam(ngaysinh1);
            ModelStaff ql1 = new ModelStaff();
            ql1.insert(nv);

            JOptionPane.showMessageDialog(this, "Lưu thành công!!!");
            loadthongtinnhanvien();
        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "error " + e.getMessage());
             JOptionPane.showMessageDialog(this, "Mã nhân viên này đã tồn tại, nếu muốn thêm với mã nhân viên này vui lòng xóa nhân viên trong db");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        Date selectedDate = jDateChooserNgaySInh.getDate();
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(selectedDate);

        int year = calendar.get(Calendar.YEAR);
        int month = calendar.get(Calendar.MONTH) + 1; // Tháng bắt đầu từ 0, nên cộng thêm 1 để có giá trị tháng thực
        int day = calendar.get(Calendar.DAY_OF_MONTH);
        String ngaysinh = year + "-" + month + "-" + day;
        
        
//        String ngay = cmbNGAY1.getSelectedItem().toString();
//        String thang = cmbTHANG1.getSelectedItem().toString();
//        String nam = cmbNAM1.getSelectedItem().toString();
//        String ngaysinh = nam + "-" + thang + "-" + ngay;
       
        Date selectedDate1 = jDateChooserNgayVaoLam.getDate();
        Calendar calendar1 = Calendar.getInstance();
        calendar1.setTime(selectedDate1);
        
        int year1 = calendar1.get(Calendar.YEAR);
        int month1 = calendar1.get(Calendar.MONTH) + 1; // Tháng bắt đầu từ 0, nên cộng thêm 1 để có giá trị tháng thực
        int day1 = calendar1.get(Calendar.DAY_OF_MONTH);
        String ngaysinh1 = year1 + "-" + month1 + "-" + day1;
     

        StringBuilder sb = new StringBuilder();
        if (txtMANHANVIEN.getText().equals("")) {
            sb.append("mã nhân viên không được để trống");
            txtMANHANVIEN.setBackground(Color.red);

        } else {
            txtMANHANVIEN.setBackground(Color.white);
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb);
        }
        if (JOptionPane.showConfirmDialog(this, "bạn có muốn sửa nhân viên không??") == JOptionPane.NO_OPTION) {
            return;
        }
        try {

            ModelStaffv2 nv = new ModelStaffv2();
            nv.setMaNV(txtMANHANVIEN.getText());
            nv.setHoNV(txtHONHANVIEN.getText());
            nv.setTenNV(txtTENNHANVIEN.getText());
            nv.setGioitinh(RBNNam.isSelected() ? 1 : 0);
            nv.setDiaChi(txtDIACHI.getText());
            nv.setNgaySinh(ngaysinh);
            nv.setDienThoai(txtSODIENTHOAI.getText());
            nv.setEmail(txtEMAIL.getText());
            nv.setNoiSinh(txtNOISINH.getText());
            nv.setNgayVaoLam(ngaysinh1);

            ModelStaff ql1 = new ModelStaff();
            ql1.update(nv);

            JOptionPane.showMessageDialog(this, "Sửa thành công!!! ");
            loadthongtinnhanvien();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void bthDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthDeleteActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if (txtMANHANVIEN.getText().equals("")) {
            sb.append("mã nhân viên không được để trống");
            txtMANHANVIEN.setBackground(Color.red);

        } else {
            txtMANHANVIEN.setBackground(Color.white);
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb);
        }
        if (JOptionPane.showConfirmDialog(this, "bạn có muốn xóa nhân viên không??") == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            ModelStaffv2 nvv = new ModelStaffv2();
            nvv.setMaNV(txtMANHANVIEN.getText());
            ModelStaff ql = new ModelStaff();
             
            ql.deletecomeroot(nvv);

            JOptionPane.showMessageDialog(this, "Xóa thành công!!! ");
            loadthongtinnhanvien();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_bthDeleteActionPerformed

    private void btnAdd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd3ActionPerformed

    private void tbNHANVIENMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNHANVIENMouseClicked
        // TODO add your handling code here:
        int row = tbNHANVIEN.getSelectedRow();

        //if (row >= 0) {
            txtMANHANVIEN.setText(tbNHANVIEN.getValueAt(row, 0).toString());
            txtHONHANVIEN.setText(tbNHANVIEN.getValueAt(row, 1).toString());
            txtTENNHANVIEN.setText(tbNHANVIEN.getValueAt(row, 2).toString());
            String gioitinh = tbNHANVIEN.getValueAt(row, 3).toString();
            if (gioitinh.equals("1")) {
                RBNNam.setSelected(true);
                RBNNNU.setSelected(false);
            } else {
                RBNNNU.setSelected(true);
                RBNNam.setSelected(false);

            }
            txtDIACHI.setText(tbNHANVIEN.getValueAt(row, 4).toString());
            String ngaysinh = tbNHANVIEN.getValueAt(row, 5).toString();
           
            txtSODIENTHOAI.setText(tbNHANVIEN.getValueAt(row, 6).toString());
            txtEMAIL.setText(tbNHANVIEN.getValueAt(row, 7).toString());
            txtNOISINH.setText(tbNHANVIEN.getValueAt(row, 8).toString());
            String ngaysinh1 = tbNHANVIEN.getValueAt(row, 9).toString();
           

           
            try {
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // Định dạng của chuỗi ngày
                Date selectedDate = dateFormat.parse(ngaysinh); // Phân tích chuỗi thành đối tượng Date
                jDateChooserNgaySInh.setDate(selectedDate); // Đặt giá trị ngày cho JDateChooser
            } catch (ParseException e) {
                e.printStackTrace();
            }
            
            try {
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // Định dạng của chuỗi ngày
                Date selectedDate = dateFormat.parse(ngaysinh1); // Phân tích chuỗi thành đối tượng Date
                jDateChooserNgayVaoLam.setDate(selectedDate); // Đặt giá trị ngày cho JDateChooser
            } catch (ParseException e) {
                e.printStackTrace();
            }

            
            
    }//GEN-LAST:event_tbNHANVIENMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
         if (rbMANHANVIEN.isSelected() == false && rbSDT.isSelected() == false && rbTENNHANVIEN.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "bạn hãy chọn tiêu chí tìm kiếm");
        } else if (rbMANHANVIEN.isSelected() == true) {

            try {

                String sql = "select * from nhanvien where manv = ? and isvisible = '1' ";
                conn = cn.getConnection();
                PreparedStatement pstmt = conn.prepareStatement(sql);

                pstmt.setString(1, txtSEARCHMANV.getText());
                ResultSet rs = pstmt.executeQuery();
                tbmodel.setRowCount(0);
                while (rs.next()) {
                    tbmodel.addRow(new Object[]{
                        rs.getString("manv"), rs.getString("honv"), rs.getString("tennv"), rs.getString("gioitinh"), rs.getString("diachi"), rs.getString("ngaysinh"), rs.getString("dienthoai"), rs.getString("email"), rs.getString("noisinh"), rs.getString("ngayvaolam") 
                    });
                }
                tbmodel.fireTableDataChanged();
                //loadthongtintaikhoan();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                e.printStackTrace();
            }

        } else if (rbSDT.isSelected() == true) {
            try {

                String sql = "select * from nhanvien where dienthoai = ? and isvisible = '1' ";
                conn = cn.getConnection();
                PreparedStatement pstmt = conn.prepareStatement(sql);

                pstmt.setString(1, txtsearchsdt.getText());
                ResultSet rs = pstmt.executeQuery();
                tbmodel.setRowCount(0);
                while (rs.next()) {
                    tbmodel.addRow(new Object[]{
                        rs.getString("manv"), rs.getString("honv"), rs.getString("tennv"), rs.getString("gioitinh"), rs.getString("diachi"), rs.getString("ngaysinh"), rs.getString("dienthoai"), rs.getString("email"), rs.getString("noisinh"), rs.getString("ngayvaolam") 
                    });
                }
                tbmodel.fireTableDataChanged();
                //loadthongtintaikhoan();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                e.printStackTrace();
            }
        } else if (rbTENNHANVIEN.isSelected() == true) {
         try {

                String sql = "select * from nhanvien where tennv = ? and isvisible = '1'  ";
                conn = cn.getConnection();
                PreparedStatement pstmt = conn.prepareStatement(sql);

                pstmt.setString(1, txtsearchtennv.getText());
                ResultSet rs = pstmt.executeQuery();
                tbmodel.setRowCount(0);
                while (rs.next()) {
                    tbmodel.addRow(new Object[]{
                        rs.getString("manv"), rs.getString("honv"), rs.getString("tennv"), rs.getString("gioitinh"), rs.getString("diachi"), rs.getString("ngaysinh"), rs.getString("dienthoai"), rs.getString("email"), rs.getString("noisinh"), rs.getString("ngayvaolam") 
                    });
                }
                tbmodel.fireTableDataChanged();
                //loadthongtintaikhoan();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        loadthongtinnhanvien();
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBNNNU;
    private javax.swing.JRadioButton RBNNam;
    private swing.Button bthDelete;
    private swing.Button btnAdd;
    private swing.Button btnAdd3;
    private swing.Button btnEdit;
    private swing.Button btnSearch;
    private swing.Button btnView;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser jDateChooserNgaySInh;
    private com.toedter.calendar.JDateChooser jDateChooserNgayVaoLam;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private swing.PanelBorder panelBorder2;
    private javax.swing.JRadioButton rbMANHANVIEN;
    private javax.swing.JRadioButton rbSDT;
    private javax.swing.JRadioButton rbTENNHANVIEN;
    private swing.RoundPanel roundPanel1;
    private swing.RoundPanel roundPanel2;
    private javax.swing.JTable tbNHANVIEN;
    private javax.swing.JTextField txtDIACHI;
    private javax.swing.JTextField txtEMAIL;
    private javax.swing.JTextField txtHONHANVIEN;
    private javax.swing.JTextField txtMANHANVIEN;
    private javax.swing.JTextField txtNOISINH;
    private javax.swing.JTextField txtSEARCHMANV;
    private javax.swing.JTextField txtSODIENTHOAI;
    private javax.swing.JTextField txtTENNHANVIEN;
    private javax.swing.JTextField txtsearchsdt;
    private javax.swing.JTextField txtsearchtennv;
    // End of variables declaration//GEN-END:variables
}
