/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import component.Header;
import component.Menu;
import event.EventShowPopupMenu;
import java.awt.Component;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;
import main.MainHome;
import net.miginfocom.swing.MigLayout;
import org.jdesktop.animation.timing.Animator;
import org.jdesktop.animation.timing.TimingTarget;
import org.jdesktop.animation.timing.TimingTargetAdapter;
import swing.MenuItem;
import swing.PopupMenu;

/**
 *
 * @author TeeDee
 */
public class FormSetting extends javax.swing.JPanel {

    /**
     * Creates new form FormSetting
     */
 
    private Menu menu;

    
    public FormSetting() {
        initComponents();
        
       
        init();
        
        // Kiểm tra giao diện hiện tại
        LookAndFeel currentLaf = UIManager.getLookAndFeel();
        if (currentLaf instanceof FlatMacLightLaf) {
            switchButton1.setSelected(false);
        } else if (currentLaf instanceof FlatMacDarkLaf) {
            // Giao diện hiện tại là FlatMacDarkLaf
            switchButton1.setSelected(true);
        } 
    }

    private void init (){
        menu = new Menu();
        int selectedIndex = jComboBox1.getSelectedIndex();
        switch (selectedIndex) {
            case 0:
                
                menu.clearMenu();
                menu.initMenuItemVietNam();
                System.out.println("case vn");
//                menu.setShowMenu(!menu.isShowMenu());
            case 1:
                menu.clearMenu();
//                menu.initMenuItemVietNam();
//                menu.clearMenu();
                menu.initMenuItem();
                System.out.println("case 2");
                
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbDark = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        switchButton1 = new swing.SwitchButton();
        lbDark1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        jLabel1.setText("jLabel1");

        lbDark.setBackground(new java.awt.Color(0, 0, 0));
        lbDark.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        lbDark.setText("Change Language");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Use darker color paletter for system backgrounds and compatible apps");

        switchButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                switchButton1MousePressed(evt);
            }
        });

        lbDark1.setBackground(new java.awt.Color(0, 0, 0));
        lbDark1.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        lbDark1.setText("Dark mode");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vietnamese", "English" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(44, 102, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbDark)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbDark1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(switchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(switchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDark1))
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDark)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void switchButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchButton1MousePressed
        // TODO add your handling code here:
        
        if (switchButton1.isSelected()){

            EventQueue.invokeLater(() -> {
            FlatAnimatedLafChange.showSnapshot();
            FlatMacLightLaf.setup();
            FlatLaf.updateUI();
            FlatAnimatedLafChange.hideSnapshotWithAnimation();
            });
        }else {
            EventQueue.invokeLater(() -> {
            FlatAnimatedLafChange.showSnapshot();
            FlatMacDarkLaf.setup();
//            FlatDarculaLaf.setup();
            FlatLaf.updateUI();
            FlatAnimatedLafChange.hideSnapshotWithAnimation();
            });
        }
    }//GEN-LAST:event_switchButton1MousePressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       
 
//        int selectedIndex = jComboBox1.getSelectedIndex();
//        switch (selectedIndex) {
//            case 0:
//                
//                menu.clearMenu();
//                menu.initMenuItemVietNam();
//                System.out.println("case vn");
////                menu.setShowMenu(!menu.isShowMenu());
//            case 1:
//                menu.clearMenu();
////                menu.initMenuItemVietNam();
////                menu.clearMenu();
//                menu.initMenuItem();
//                System.out.println("case 2");
//                
//        }
        init();

    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbDark;
    private javax.swing.JLabel lbDark1;
    private swing.SwitchButton switchButton1;
    // End of variables declaration//GEN-END:variables
}
