/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package component;

import event.EventColorChange;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JButton;

/**
 *
 * @author TeeDee
 */
public class ColorOption extends javax.swing.JPanel {

   public EventColorChange getEvent() {
        return event;
    }

    public void setEvent(EventColorChange event) {
        this.event = event;
    }

    private EventColorChange event;

    public ColorOption() {
        initComponents();
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonSetting3 = new swing.ButtonSetting();
        buttonSetting4 = new swing.ButtonSetting();
        buttonSetting5 = new swing.ButtonSetting();
        buttonSetting6 = new swing.ButtonSetting();
        buttonSetting7 = new swing.ButtonSetting();

        buttonSetting3.setBackground(new java.awt.Color(50, 200, 126));

        buttonSetting4.setBackground(new java.awt.Color(253, 83, 83));

        buttonSetting5.setBackground(new java.awt.Color(227, 185, 71));

        buttonSetting6.setBackground(new java.awt.Color(128, 41, 232));

        buttonSetting7.setBackground(new java.awt.Color(54, 149, 255));
        buttonSetting7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/color_check.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonSetting4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSetting3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSetting6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSetting5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSetting7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonSetting4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(buttonSetting3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(buttonSetting6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(buttonSetting5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(buttonSetting7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
 private void setSelected(JButton cmd) {
        event.colorChange(cmd.getBackground());
        for (Component com : getComponents()) {
            JButton cm = (JButton) com;
            cm.setIcon(null);
        }
        cmd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/color_check.png")));

    }

    public void setSelectedColor(Color color) {
        for (Component com : getComponents()) {
            if (com.getBackground().getRGB() == color.getRGB()) {
                setSelected((JButton) com);
                break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonSetting buttonSetting3;
    private swing.ButtonSetting buttonSetting4;
    private swing.ButtonSetting buttonSetting5;
    private swing.ButtonSetting buttonSetting6;
    private swing.ButtonSetting buttonSetting7;
    // End of variables declaration//GEN-END:variables
}
